# Generated by Django 3.1.5 on 2021-01-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20210121_1803'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='about',
            managers=[
            ],
        ),
    ]
