# Generated by Django 3.1.5 on 2021-01-23 02:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice', '0002_auto_20210123_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='voter',
            field=models.ManyToManyField(related_name='notice_voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
