# Generated by Django 3.1.5 on 2021-01-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soogle', '0003_auto_20210117_0323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '댓글', 'verbose_name_plural': '댓글'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='댓글',
        ),
    ]
