# Generated by Django 3.1.5 on 2021-01-21 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soogle', '0004_auto_20210118_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(verbose_name='문의사항')),
                ('create_date', models.DateTimeField(verbose_name='등록시간')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정시간')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_about', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '문의사항',
                'verbose_name_plural': '문의사항',
                'db_table': '문의사항',
            },
        ),
    ]
