# Generated by Django 3.1.5 on 2021-01-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soogle', '0005_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
